// Mocks generated by Mockito 5.4.6 from annotations
// in provider_mvvm_example/test/features/settings/setting_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:provider_mvvm_example/src/common/services/storage_service.dart'
    as _i3;
import 'package:provider_mvvm_example/src/features/settings/models/setting_model.dart'
    as _i2;
import 'package:provider_mvvm_example/src/features/settings/repositories/setting_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingModel_0 extends _i1.SmartFake implements _i2.SettingModel {
  _FakeSettingModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initStorage() =>
      (super.noSuchMethod(
            Invocation.method(#initStorage, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getBoolValue({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#getBoolValue, [], {#key: key}),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setBoolValue({required String? key, required bool? value}) =>
      (super.noSuchMethod(
            Invocation.method(#setBoolValue, [], {#key: key, #value: value}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeValue({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removeValue, [], {#key: key}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearStorage() =>
      (super.noSuchMethod(
            Invocation.method(#clearStorage, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SettingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingRepository extends _i1.Mock implements _i5.SettingRepository {
  MockSettingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SettingModel> readTheme() =>
      (super.noSuchMethod(
            Invocation.method(#readTheme, []),
            returnValue: _i4.Future<_i2.SettingModel>.value(
              _FakeSettingModel_0(this, Invocation.method(#readTheme, [])),
            ),
          )
          as _i4.Future<_i2.SettingModel>);

  @override
  _i4.Future<void> updateTheme({required bool? isDarkTheme}) =>
      (super.noSuchMethod(
            Invocation.method(#updateTheme, [], {#isDarkTheme: isDarkTheme}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
