// Mocks generated by Mockito 5.4.6 from annotations
// in provider_mvvm_example/test/features/users/user_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:provider_mvvm_example/src/common/patterns/result_pattern.dart'
    as _i6;
import 'package:provider_mvvm_example/src/common/services/connection_service.dart'
    as _i2;
import 'package:provider_mvvm_example/src/common/services/http_service.dart'
    as _i4;
import 'package:provider_mvvm_example/src/features/users/models/user_model.dart'
    as _i7;
import 'package:provider_mvvm_example/src/features/users/repositories/user_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i2.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> checkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnection, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i4.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({Object? data, String? error, int? statusCode})> getData({
    required String? path,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#path: path}),
            returnValue:
                _i3.Future<
                  ({Object? data, String? error, int? statusCode})
                >.value((data: null, error: null, statusCode: null)),
          )
          as _i3.Future<({Object? data, String? error, int? statusCode})>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i5.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<List<_i7.UserModel>, Exception>> findAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#findAllUsers, []),
            returnValue:
                _i3.Future<_i6.Result<List<_i7.UserModel>, Exception>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.UserModel>, Exception>>(
                    this,
                    Invocation.method(#findAllUsers, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<List<_i7.UserModel>, Exception>>);
}
